spring.application.name=campus-platform-server

server.port=9001
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/campus_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

app.jwt.secret=CampusPlatformJwtSecretKeyCampusPlatformJwtSecretKey
app.jwt.expire-days=7
app.file.storage-path=storage/uploads
app.file.public-base-url=http://localhost:9001/api/files/view/
app.errand.urgent-fee=2.00
app.errand.fragile-fee=3.00
app.errand.publish-limit-per-user=3
app.errand.accept-limit-per-user=5
app.errand.auto-expire-hours=4
app.errand.min-base-fee=1.00
app.errand.max-base-fee=50.00
